### ISSUE TITLE
Escolher e configurar uma ferramenta de analise estatica

### ISSUE THREAD

**Issue by gabibguedes** [gabibguedes/LUP-Tecprog#7]
Escolher uma ferramenta de analise estática compatível com C++ para aplicar ao código. Obs.: CodeClimate não é compatível com C++.

Possível escolha: Codacy?

**Comment by gabibguedes** [comment]
analizo http://www.analizo.org/features.html - by Eduardo

**Comment by vitorl-s** [comment]
Cppcheck é uma opção também

**Comment by gabibguedes** [comment]
Escolhidos = Codacy e cppcheck

**Comment by gabibguedes** [comment]
link codacy: https://app.codacy.com/project/gabibguedes/LUP-Tecprog/dashboard?branchId=8647487

**Comment by gabibguedes** [comment]
link para instalar o cppcheck: http://cppcheck.sourceforge.net/
